# fly.toml app configuration file generated for api-cache on 2025-04-01T08:40:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-cache'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'
  TANSHU_API_HOST = 'https://api.tanshuapi.com'
  DB_FILE_PATH = "/opt/data/remote-cache.sqlite"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mount]
  source = "appdata"
  destination = "/opt/data"